source ~/.local/share/omakub/defaults/zsh/rc

# Editor used by CLI
export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"

# Optional machine/user specific overrides
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
